### ISSUE TITLE
[Suggestion] Skip if the card ID is not found in the webpage database

### ISSUE THREAD

**Issue by Lahrenheit** [AlexsanderRST/edopro-hq-pics-downloader#5]
Hello alex, I write here a suggestion for a future update, will be awesome add **skip if the card ID is not found in the webpage database** so no crash the downloader, thanks, keep it up!

**Comment by AlexsanderRST** [comment]
Thanks for report. I'll take this week to reformulate the program and fix this issue.

**Comment by AlexsanderRST** [comment]
Apparently the problem was fixed in the version I posted today. I tested it twice, once with the old allcards.ydk (~10k cards) and once with the updated one (~11k cards).  If it still crashing to you, send me the ydk file to checkup.

**Comment by Lahrenheit** [comment]
I'm testing with download all cards of your updated ydk file; the option "all fields" crash the program at 62/244, other time at 143/244

**Comment by Lahrenheit** [comment]
The error that appear to me is "failed to execute script hd_cards_dwnlder" in "all fields" option when it freeze

**Comment by AlexsanderRST** [comment]
I tested few times and got this error only when: 
- I shutdown the web;
- I closed more than two programs when there were two or more open.

Try to cleanout your field pics folder and check if your connection is stable before run the program. If you have more time, follow these steps:
- Download Python 3;
- At cmd: *pip install pygame*;
- Download the .py file and put it at your game folder (same as the exe);
- Right-click at the file and *Edit with IDLE*;
- Go to Run > Run Module or press F5;
- The program will open with a SHELL;
- Try to download all fields again and if a error popups at SHELL, type here the error or send me a print.

I'll run more test to see if I can catch this error to add an Exception.
